#!/usr/bin/env python3
"""Generate Ansible inventory from Terraform outputs.
Usage: python3 scripts/generate-inventory.py
Reads terraform output from both environments and writes inventory/hosts.yml
"""
import json, subprocess, sys, os

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def tf_output(env_dir):
    try:
        result = subprocess.run(
            ["terraform", "output", "-json"],
            capture_output=True, text=True, cwd=env_dir
        )
        if result.returncode == 0:
            return json.loads(result.stdout) if result.stdout.strip() else {}
    except Exception:
        pass
    return {}

def get_val(outputs, key):
    if key in outputs:
        return outputs[key].get("value", "")
    return ""

shared = tf_output(os.path.join(REPO_ROOT, "environments", "shared"))
cv = tf_output(os.path.join(REPO_ROOT, "environments", "project-cv"))

nginx_ip = get_val(shared, "nginx_public_ip")
vpn_gw_name = get_val(shared, "vpn_gw_vm_name")
web_cv_name = get_val(cv, "vm_name")
web_cv_ip = get_val(cv, "vm_ip")

if not nginx_ip:
    print("Warning: Could not get DO edge IP from shared state", file=sys.stderr)
    nginx_ip = "UNKNOWN"

inventory = f"""# Auto-generated by scripts/generate-inventory.py
# Do not edit manually — run: python3 scripts/generate-inventory.py

all:
  children:
    do_edge:
      hosts:
        nginx:
          ansible_host: {nginx_ip}
          ansible_user: root
          ansible_ssh_private_key_file: ../../keys/hybrid-infra-admin
    proxmox_vms:
      hosts:
        vpn_gw:
          ansible_host: 192.168.0.106
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ../../keys/hybrid-infra-admin
          role: vpn-gateway
        web_cv:
          ansible_host: {web_cv_ip or '192.168.0.105'}
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ../../keys/hybrid-infra-admin
          role: web-cv
          site_repo: https://github.com/Laurentcadieux/LaurentCadieuxDOTonline.git
          site_domain: laurentcadieux.online
"""

out_path = os.path.join(REPO_ROOT, "inventory", "hosts.yml")
with open(out_path, "w") as f:
    f.write(inventory)

print(f"✅ Inventory written to {out_path}")
print(f"   DO edge: {nginx_ip}")
print(f"   VPN GW:  192.168.0.106")
print(f"   web-CV:  {web_cv_ip or '192.168.0.105'}")
